### ISSUE TITLE
Breaks the UI in both Ilias-v5.4 and v6.x

### ISSUE THREAD

**Issue by ellamkhtj** [frankbauer/ilias-asscodequestion#10]
Every time a user changes to a CodeQuestion, either as examiner or as student taking a test, the Ilias-UI breaks. For example there are changes in the Font for the whole page or some page elements in the TopBar, like the Profile, Search and Message center, are shown in the left. See also the screenshots, the files ending in "otherQuestion" should show how the UI is expected to be.
We are also testing the plugin in our Ilias6 demo server and until now, the plugin seems overall compatible with that version and we have observed only the issues with the UI. Will there be an official release for the newest Ilias versions, such as Ilias6 or 7?

![Ilias5 4 21-CodeQuestion](https://user-images.githubusercontent.com/43756316/119953727-975b1980-bf9e-11eb-90b9-e6ba362b6a4b.png)
![Ilias5 4 21-otherQuestion](https://user-images.githubusercontent.com/43756316/119953744-9d50fa80-bf9e-11eb-9433-49c74f184daf.png)
![Ilias6 x-CodeQuestion](https://user-images.githubusercontent.com/43756316/119953751-9fb35480-bf9e-11eb-8068-b4f57b8e3396.png)
![Ilias6 x-otherQuestion](https://user-images.githubusercontent.com/43756316/119953776-a5a93580-bf9e-11eb-9e11-a389b5fa6204.png)

**Comment by frankbauer** [comment]
Sorry for the long delay. I'll have a look at the css polution. And I am currently upgrading the plugin to ilias 7.
