### ISSUE TITLE
License

### ISSUE THREAD

**Issue by glor** [frankbauer/ilias-asscodequestion#5]
I noticed that your license is not granting any rights/permissions, not even for using the software. Is that intentionally? It seams like it is only part of the MIT license but the first paragraph is missing

**Comment by frankbauer** [comment]
No, that is not intentional.

**Comment by frankbauer** [comment]
Thanks for bringing this to my attention!

Fixed with 29d632c1cb55fadc51c3aefde91ad40038a62f3b.
