### ISSUE TITLE
 Class File Missing (class.ilasscodequestionPlugin.php)

### ISSUE THREAD

**Issue by GRRRR11** [frankbauer/ilias-asscodequestion#7]
Tried to install the plugin an ILIAS 5.2. Whenever I try to activate the plugin it crashes, the info says, there is a class file missing (class.ilasscodequestionPlugin.php). What did I do wrong?
[posv5_1359.log](https://github.com/frankbauer/ilias-asscodequestion/files/3558899/posv5_1359.log)

**Comment by frankbauer** [comment]
I am sorry, but we do not test with older ilias instances and thus I do not have an older installation at hand. 

I know that this Version worked in 5.2: 29371ee99083f93ca3ccfcaa41e703c8d3cf16d0 
Could you maybe test that version to make sure it is a Problem with the plugin and not the installation?
